### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by aabytt** [aabytt/custom-screensaver-aerial#4]
* [x] handler for stalled status of video to avoid possible burn out of oled panel 
* [x] source video quality option picker in main panel 
* [x] fade in/out effect for a smooth transition of videos 
* [x] disable Dolby Vision pop-up on video start (it turns screensaver off)
* [x] add locale setting for OSD 
* [ ] autodetect locale option
* [ ] add categories and option to filter playlist by category
* [ ] option to pick custom location of media files (i.e. usb drive or local media server)
* [ ] separate OSD opacity settings for SDR/HDR source
* [ ] optional weather OSD (IP-based detection or manual city input))
* [ ] font selection setting
* [ ] port to Flutter for webOS 24+ (9+) support
* [ ] option to add extra 3rd-party video sources

**Comment by VoodooZ** [comment]
Maybe make the OSD text optional as it's an OLED so I don't want anything static on the screen. THanks.

**Comment by aabytt** [comment]
> Maybe make the OSD text optional as it's an OLED so I don't want anything static on the screen. THanks.

You can set OSD opacity to 0% and it will be invisible )

**Comment by ghost** [comment]
add a way to toggle between 12 hour and 24 hour?

**Comment by aabytt** [comment]
Which language locale are you using?

**Comment by aabytt** [comment]
app get's time format from webOS according to selected locale, e.g. US English will display 12 hour format
